//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.ServiceTicket {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTicket.WebServiceTicketSoap")]
    public interface WebServiceTicketSoap {
        
        // CODEGEN: Generating message contract since message GetPriceTicketRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPriceTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        B2B.ServiceTicket.GetPriceTicketResponse GetPriceTicket(B2B.ServiceTicket.GetPriceTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPriceTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<B2B.ServiceTicket.GetPriceTicketResponse> GetPriceTicketAsync(B2B.ServiceTicket.GetPriceTicketRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPriceTicket", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPriceTicketRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public B2B.ServiceTicket.AuthHeader AuthHeader;
        
        public GetPriceTicketRequest() {
        }
        
        public GetPriceTicketRequest(B2B.ServiceTicket.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPriceTicketResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPriceTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetPriceTicketResult;
        
        public GetPriceTicketResponse() {
        }
        
        public GetPriceTicketResponse(string GetPriceTicketResult) {
            this.GetPriceTicketResult = GetPriceTicketResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTicketSoapChannel : B2B.ServiceTicket.WebServiceTicketSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTicketSoapClient : System.ServiceModel.ClientBase<B2B.ServiceTicket.WebServiceTicketSoap>, B2B.ServiceTicket.WebServiceTicketSoap {
        
        public WebServiceTicketSoapClient() {
        }
        
        public WebServiceTicketSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTicketSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTicketSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTicketSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2B.ServiceTicket.GetPriceTicketResponse B2B.ServiceTicket.WebServiceTicketSoap.GetPriceTicket(B2B.ServiceTicket.GetPriceTicketRequest request) {
            return base.Channel.GetPriceTicket(request);
        }
        
        public string GetPriceTicket(B2B.ServiceTicket.AuthHeader AuthHeader) {
            B2B.ServiceTicket.GetPriceTicketRequest inValue = new B2B.ServiceTicket.GetPriceTicketRequest();
            inValue.AuthHeader = AuthHeader;
            B2B.ServiceTicket.GetPriceTicketResponse retVal = ((B2B.ServiceTicket.WebServiceTicketSoap)(this)).GetPriceTicket(inValue);
            return retVal.GetPriceTicketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2B.ServiceTicket.GetPriceTicketResponse> B2B.ServiceTicket.WebServiceTicketSoap.GetPriceTicketAsync(B2B.ServiceTicket.GetPriceTicketRequest request) {
            return base.Channel.GetPriceTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2B.ServiceTicket.GetPriceTicketResponse> GetPriceTicketAsync(B2B.ServiceTicket.AuthHeader AuthHeader) {
            B2B.ServiceTicket.GetPriceTicketRequest inValue = new B2B.ServiceTicket.GetPriceTicketRequest();
            inValue.AuthHeader = AuthHeader;
            return ((B2B.ServiceTicket.WebServiceTicketSoap)(this)).GetPriceTicketAsync(inValue);
        }
    }
}
