//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.ServiceAuth {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAuth.WebServiceAuthSoap")]
    public interface WebServiceAuthSoap {
        
        // CODEGEN: Generating message contract since message AuthUserRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        B2B.ServiceAuth.AuthUserResponse AuthUser(B2B.ServiceAuth.AuthUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthUser", ReplyAction="*")]
        System.Threading.Tasks.Task<B2B.ServiceAuth.AuthUserResponse> AuthUserAsync(B2B.ServiceAuth.AuthUserRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public B2B.ServiceAuth.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string iv_tc_tax_no;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string iv_tel_no;
        
        public AuthUserRequest() {
        }
        
        public AuthUserRequest(B2B.ServiceAuth.AuthHeader AuthHeader, string iv_tc_tax_no, string iv_tel_no) {
            this.AuthHeader = AuthHeader;
            this.iv_tc_tax_no = iv_tc_tax_no;
            this.iv_tel_no = iv_tel_no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AuthUserResult;
        
        public AuthUserResponse() {
        }
        
        public AuthUserResponse(string AuthUserResult) {
            this.AuthUserResult = AuthUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceAuthSoapChannel : B2B.ServiceAuth.WebServiceAuthSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceAuthSoapClient : System.ServiceModel.ClientBase<B2B.ServiceAuth.WebServiceAuthSoap>, B2B.ServiceAuth.WebServiceAuthSoap {
        
        public WebServiceAuthSoapClient() {
        }
        
        public WebServiceAuthSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceAuthSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAuthSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAuthSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2B.ServiceAuth.AuthUserResponse B2B.ServiceAuth.WebServiceAuthSoap.AuthUser(B2B.ServiceAuth.AuthUserRequest request) {
            return base.Channel.AuthUser(request);
        }
        
        public string AuthUser(B2B.ServiceAuth.AuthHeader AuthHeader, string iv_tc_tax_no, string iv_tel_no) {
            B2B.ServiceAuth.AuthUserRequest inValue = new B2B.ServiceAuth.AuthUserRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.iv_tc_tax_no = iv_tc_tax_no;
            inValue.iv_tel_no = iv_tel_no;
            B2B.ServiceAuth.AuthUserResponse retVal = ((B2B.ServiceAuth.WebServiceAuthSoap)(this)).AuthUser(inValue);
            return retVal.AuthUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2B.ServiceAuth.AuthUserResponse> B2B.ServiceAuth.WebServiceAuthSoap.AuthUserAsync(B2B.ServiceAuth.AuthUserRequest request) {
            return base.Channel.AuthUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2B.ServiceAuth.AuthUserResponse> AuthUserAsync(B2B.ServiceAuth.AuthHeader AuthHeader, string iv_tc_tax_no, string iv_tel_no) {
            B2B.ServiceAuth.AuthUserRequest inValue = new B2B.ServiceAuth.AuthUserRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.iv_tc_tax_no = iv_tc_tax_no;
            inValue.iv_tel_no = iv_tel_no;
            return ((B2B.ServiceAuth.WebServiceAuthSoap)(this)).AuthUserAsync(inValue);
        }
    }
}
