//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.ServiceShipment {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceShipment.WebServiceShipmentSoap")]
    public interface WebServiceShipmentSoap {
        
        // CODEGEN: Generating message contract since message GetShipmentsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetShipments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        B2B.ServiceShipment.GetShipmentsResponse GetShipments(B2B.ServiceShipment.GetShipmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetShipments", ReplyAction="*")]
        System.Threading.Tasks.Task<B2B.ServiceShipment.GetShipmentsResponse> GetShipmentsAsync(B2B.ServiceShipment.GetShipmentsRequest request);
        
        // CODEGEN: Generating message contract since message GetShipmentDetailsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetShipmentDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        B2B.ServiceShipment.GetShipmentDetailsResponse GetShipmentDetails(B2B.ServiceShipment.GetShipmentDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetShipmentDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<B2B.ServiceShipment.GetShipmentDetailsResponse> GetShipmentDetailsAsync(B2B.ServiceShipment.GetShipmentDetailsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetShipments", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetShipmentsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public B2B.ServiceShipment.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] lst_kunnr;
        
        public GetShipmentsRequest() {
        }
        
        public GetShipmentsRequest(B2B.ServiceShipment.AuthHeader AuthHeader, string[] lst_kunnr) {
            this.AuthHeader = AuthHeader;
            this.lst_kunnr = lst_kunnr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetShipmentsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetShipmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetShipmentsResult;
        
        public GetShipmentsResponse() {
        }
        
        public GetShipmentsResponse(string GetShipmentsResult) {
            this.GetShipmentsResult = GetShipmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetShipmentDetails", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetShipmentDetailsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public B2B.ServiceShipment.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string iv_tknum;
        
        public GetShipmentDetailsRequest() {
        }
        
        public GetShipmentDetailsRequest(B2B.ServiceShipment.AuthHeader AuthHeader, string iv_tknum) {
            this.AuthHeader = AuthHeader;
            this.iv_tknum = iv_tknum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetShipmentDetailsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetShipmentDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetShipmentDetailsResult;
        
        public GetShipmentDetailsResponse() {
        }
        
        public GetShipmentDetailsResponse(string GetShipmentDetailsResult) {
            this.GetShipmentDetailsResult = GetShipmentDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceShipmentSoapChannel : B2B.ServiceShipment.WebServiceShipmentSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceShipmentSoapClient : System.ServiceModel.ClientBase<B2B.ServiceShipment.WebServiceShipmentSoap>, B2B.ServiceShipment.WebServiceShipmentSoap {
        
        public WebServiceShipmentSoapClient() {
        }
        
        public WebServiceShipmentSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceShipmentSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceShipmentSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceShipmentSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2B.ServiceShipment.GetShipmentsResponse B2B.ServiceShipment.WebServiceShipmentSoap.GetShipments(B2B.ServiceShipment.GetShipmentsRequest request) {
            return base.Channel.GetShipments(request);
        }
        
        public string GetShipments(B2B.ServiceShipment.AuthHeader AuthHeader, string[] lst_kunnr) {
            B2B.ServiceShipment.GetShipmentsRequest inValue = new B2B.ServiceShipment.GetShipmentsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.lst_kunnr = lst_kunnr;
            B2B.ServiceShipment.GetShipmentsResponse retVal = ((B2B.ServiceShipment.WebServiceShipmentSoap)(this)).GetShipments(inValue);
            return retVal.GetShipmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2B.ServiceShipment.GetShipmentsResponse> B2B.ServiceShipment.WebServiceShipmentSoap.GetShipmentsAsync(B2B.ServiceShipment.GetShipmentsRequest request) {
            return base.Channel.GetShipmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2B.ServiceShipment.GetShipmentsResponse> GetShipmentsAsync(B2B.ServiceShipment.AuthHeader AuthHeader, string[] lst_kunnr) {
            B2B.ServiceShipment.GetShipmentsRequest inValue = new B2B.ServiceShipment.GetShipmentsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.lst_kunnr = lst_kunnr;
            return ((B2B.ServiceShipment.WebServiceShipmentSoap)(this)).GetShipmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2B.ServiceShipment.GetShipmentDetailsResponse B2B.ServiceShipment.WebServiceShipmentSoap.GetShipmentDetails(B2B.ServiceShipment.GetShipmentDetailsRequest request) {
            return base.Channel.GetShipmentDetails(request);
        }
        
        public string GetShipmentDetails(B2B.ServiceShipment.AuthHeader AuthHeader, string iv_tknum) {
            B2B.ServiceShipment.GetShipmentDetailsRequest inValue = new B2B.ServiceShipment.GetShipmentDetailsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.iv_tknum = iv_tknum;
            B2B.ServiceShipment.GetShipmentDetailsResponse retVal = ((B2B.ServiceShipment.WebServiceShipmentSoap)(this)).GetShipmentDetails(inValue);
            return retVal.GetShipmentDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2B.ServiceShipment.GetShipmentDetailsResponse> B2B.ServiceShipment.WebServiceShipmentSoap.GetShipmentDetailsAsync(B2B.ServiceShipment.GetShipmentDetailsRequest request) {
            return base.Channel.GetShipmentDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2B.ServiceShipment.GetShipmentDetailsResponse> GetShipmentDetailsAsync(B2B.ServiceShipment.AuthHeader AuthHeader, string iv_tknum) {
            B2B.ServiceShipment.GetShipmentDetailsRequest inValue = new B2B.ServiceShipment.GetShipmentDetailsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.iv_tknum = iv_tknum;
            return ((B2B.ServiceShipment.WebServiceShipmentSoap)(this)).GetShipmentDetailsAsync(inValue);
        }
    }
}
