//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.ServiceQdms {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://services.alfemo.com.tr/", ConfigurationName="ServiceQdms.AlfemoWebSiteServiceSoap")]
    public interface AlfemoWebSiteServiceSoap {
        
        // CODEGEN: Generating message contract since message AlfemoFiyatListesiJSONRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://services.alfemo.com.tr/AlfemoFiyatListesiJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        B2B.ServiceQdms.AlfemoFiyatListesiJSONResponse AlfemoFiyatListesiJSON(B2B.ServiceQdms.AlfemoFiyatListesiJSONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://services.alfemo.com.tr/AlfemoFiyatListesiJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoFiyatListesiJSONResponse> AlfemoFiyatListesiJSONAsync(B2B.ServiceQdms.AlfemoFiyatListesiJSONRequest request);
        
        // CODEGEN: Generating message contract since message AlfemoDepoStokJSONRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://services.alfemo.com.tr/AlfemoDepoStokJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        B2B.ServiceQdms.AlfemoDepoStokJSONResponse AlfemoDepoStokJSON(B2B.ServiceQdms.AlfemoDepoStokJSONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://services.alfemo.com.tr/AlfemoDepoStokJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoDepoStokJSONResponse> AlfemoDepoStokJSONAsync(B2B.ServiceQdms.AlfemoDepoStokJSONRequest request);
        
        // CODEGEN: Generating message contract since message AlfemoAcikSiparisJSONRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://services.alfemo.com.tr/AlfemoAcikSiparisJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        B2B.ServiceQdms.AlfemoAcikSiparisJSONResponse AlfemoAcikSiparisJSON(B2B.ServiceQdms.AlfemoAcikSiparisJSONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://services.alfemo.com.tr/AlfemoAcikSiparisJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoAcikSiparisJSONResponse> AlfemoAcikSiparisJSONAsync(B2B.ServiceQdms.AlfemoAcikSiparisJSONRequest request);
        
        // CODEGEN: Generating message contract since message AlfemoSiparisSorgulamaJSONRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://services.alfemo.com.tr/AlfemoSiparisSorgulamaJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        B2B.ServiceQdms.AlfemoSiparisSorgulamaJSONResponse AlfemoSiparisSorgulamaJSON(B2B.ServiceQdms.AlfemoSiparisSorgulamaJSONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://services.alfemo.com.tr/AlfemoSiparisSorgulamaJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoSiparisSorgulamaJSONResponse> AlfemoSiparisSorgulamaJSONAsync(B2B.ServiceQdms.AlfemoSiparisSorgulamaJSONRequest request);
        
        // CODEGEN: Generating message contract since message AlfemoUrunJSONRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://services.alfemo.com.tr/AlfemoUrunJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        B2B.ServiceQdms.AlfemoUrunJSONResponse AlfemoUrunJSON(B2B.ServiceQdms.AlfemoUrunJSONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://services.alfemo.com.tr/AlfemoUrunJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoUrunJSONResponse> AlfemoUrunJSONAsync(B2B.ServiceQdms.AlfemoUrunJSONRequest request);
        
        // CODEGEN: Generating message contract since message AlfemoIletisimRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://services.alfemo.com.tr/AlfemoIletisim", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        B2B.ServiceQdms.AlfemoIletisimResponse AlfemoIletisim(B2B.ServiceQdms.AlfemoIletisimRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://services.alfemo.com.tr/AlfemoIletisim", ReplyAction="*")]
        System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoIletisimResponse> AlfemoIletisimAsync(B2B.ServiceQdms.AlfemoIletisimRequest request);
        
        // CODEGEN: Generating message contract since message AlfemoUrunMontajPdfRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://services.alfemo.com.tr/AlfemoUrunMontajPdf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        B2B.ServiceQdms.AlfemoUrunMontajPdfResponse AlfemoUrunMontajPdf(B2B.ServiceQdms.AlfemoUrunMontajPdfRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://services.alfemo.com.tr/AlfemoUrunMontajPdf", ReplyAction="*")]
        System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoUrunMontajPdfResponse> AlfemoUrunMontajPdfAsync(B2B.ServiceQdms.AlfemoUrunMontajPdfRequest request);
        
        // CODEGEN: Generating message contract since message AlfemoUrunPdfRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://services.alfemo.com.tr/AlfemoUrunPdf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        B2B.ServiceQdms.AlfemoUrunPdfResponse AlfemoUrunPdf(B2B.ServiceQdms.AlfemoUrunPdfRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://services.alfemo.com.tr/AlfemoUrunPdf", ReplyAction="*")]
        System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoUrunPdfResponse> AlfemoUrunPdfAsync(B2B.ServiceQdms.AlfemoUrunPdfRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://services.alfemo.com.tr/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlfemoFiyatListesiJSON", WrapperNamespace="https://services.alfemo.com.tr/", IsWrapped=true)]
    public partial class AlfemoFiyatListesiJSONRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://services.alfemo.com.tr/")]
        public B2B.ServiceQdms.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=0)]
        public string UrunKodu;
        
        public AlfemoFiyatListesiJSONRequest() {
        }
        
        public AlfemoFiyatListesiJSONRequest(B2B.ServiceQdms.AuthHeader AuthHeader, string UrunKodu) {
            this.AuthHeader = AuthHeader;
            this.UrunKodu = UrunKodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlfemoFiyatListesiJSONResponse", WrapperNamespace="https://services.alfemo.com.tr/", IsWrapped=true)]
    public partial class AlfemoFiyatListesiJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=0)]
        public string AlfemoFiyatListesiJSONResult;
        
        public AlfemoFiyatListesiJSONResponse() {
        }
        
        public AlfemoFiyatListesiJSONResponse(string AlfemoFiyatListesiJSONResult) {
            this.AlfemoFiyatListesiJSONResult = AlfemoFiyatListesiJSONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlfemoDepoStokJSON", WrapperNamespace="https://services.alfemo.com.tr/", IsWrapped=true)]
    public partial class AlfemoDepoStokJSONRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://services.alfemo.com.tr/")]
        public B2B.ServiceQdms.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=0)]
        public string UrunKodu;
        
        public AlfemoDepoStokJSONRequest() {
        }
        
        public AlfemoDepoStokJSONRequest(B2B.ServiceQdms.AuthHeader AuthHeader, string UrunKodu) {
            this.AuthHeader = AuthHeader;
            this.UrunKodu = UrunKodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlfemoDepoStokJSONResponse", WrapperNamespace="https://services.alfemo.com.tr/", IsWrapped=true)]
    public partial class AlfemoDepoStokJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=0)]
        public string AlfemoDepoStokJSONResult;
        
        public AlfemoDepoStokJSONResponse() {
        }
        
        public AlfemoDepoStokJSONResponse(string AlfemoDepoStokJSONResult) {
            this.AlfemoDepoStokJSONResult = AlfemoDepoStokJSONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlfemoAcikSiparisJSON", WrapperNamespace="https://services.alfemo.com.tr/", IsWrapped=true)]
    public partial class AlfemoAcikSiparisJSONRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://services.alfemo.com.tr/")]
        public B2B.ServiceQdms.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=0)]
        public string SiparisNo;
        
        public AlfemoAcikSiparisJSONRequest() {
        }
        
        public AlfemoAcikSiparisJSONRequest(B2B.ServiceQdms.AuthHeader AuthHeader, string SiparisNo) {
            this.AuthHeader = AuthHeader;
            this.SiparisNo = SiparisNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlfemoAcikSiparisJSONResponse", WrapperNamespace="https://services.alfemo.com.tr/", IsWrapped=true)]
    public partial class AlfemoAcikSiparisJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=0)]
        public string AlfemoAcikSiparisJSONResult;
        
        public AlfemoAcikSiparisJSONResponse() {
        }
        
        public AlfemoAcikSiparisJSONResponse(string AlfemoAcikSiparisJSONResult) {
            this.AlfemoAcikSiparisJSONResult = AlfemoAcikSiparisJSONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlfemoSiparisSorgulamaJSON", WrapperNamespace="https://services.alfemo.com.tr/", IsWrapped=true)]
    public partial class AlfemoSiparisSorgulamaJSONRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://services.alfemo.com.tr/")]
        public B2B.ServiceQdms.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=0)]
        public string SiparisNo;
        
        public AlfemoSiparisSorgulamaJSONRequest() {
        }
        
        public AlfemoSiparisSorgulamaJSONRequest(B2B.ServiceQdms.AuthHeader AuthHeader, string SiparisNo) {
            this.AuthHeader = AuthHeader;
            this.SiparisNo = SiparisNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlfemoSiparisSorgulamaJSONResponse", WrapperNamespace="https://services.alfemo.com.tr/", IsWrapped=true)]
    public partial class AlfemoSiparisSorgulamaJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=0)]
        public string AlfemoSiparisSorgulamaJSONResult;
        
        public AlfemoSiparisSorgulamaJSONResponse() {
        }
        
        public AlfemoSiparisSorgulamaJSONResponse(string AlfemoSiparisSorgulamaJSONResult) {
            this.AlfemoSiparisSorgulamaJSONResult = AlfemoSiparisSorgulamaJSONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlfemoUrunJSON", WrapperNamespace="https://services.alfemo.com.tr/", IsWrapped=true)]
    public partial class AlfemoUrunJSONRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://services.alfemo.com.tr/")]
        public B2B.ServiceQdms.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=0)]
        public string UrunKodu;
        
        public AlfemoUrunJSONRequest() {
        }
        
        public AlfemoUrunJSONRequest(B2B.ServiceQdms.AuthHeader AuthHeader, string UrunKodu) {
            this.AuthHeader = AuthHeader;
            this.UrunKodu = UrunKodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlfemoUrunJSONResponse", WrapperNamespace="https://services.alfemo.com.tr/", IsWrapped=true)]
    public partial class AlfemoUrunJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=0)]
        public string AlfemoUrunJSONResult;
        
        public AlfemoUrunJSONResponse() {
        }
        
        public AlfemoUrunJSONResponse(string AlfemoUrunJSONResult) {
            this.AlfemoUrunJSONResult = AlfemoUrunJSONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlfemoIletisim", WrapperNamespace="https://services.alfemo.com.tr/", IsWrapped=true)]
    public partial class AlfemoIletisimRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://services.alfemo.com.tr/")]
        public B2B.ServiceQdms.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=0)]
        public string Konu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=1)]
        public string AltKonu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=2)]
        public string Ad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=3)]
        public string Soyad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=4)]
        public string Eposta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=5)]
        public string Telefon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=6)]
        public string Adres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=7)]
        public string SehirKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=8)]
        public string Sehir;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=9)]
        public string IlceKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=10)]
        public string Ilce;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=11)]
        public string Mesaj;
        
        public AlfemoIletisimRequest() {
        }
        
        public AlfemoIletisimRequest(B2B.ServiceQdms.AuthHeader AuthHeader, string Konu, string AltKonu, string Ad, string Soyad, string Eposta, string Telefon, string Adres, string SehirKodu, string Sehir, string IlceKodu, string Ilce, string Mesaj) {
            this.AuthHeader = AuthHeader;
            this.Konu = Konu;
            this.AltKonu = AltKonu;
            this.Ad = Ad;
            this.Soyad = Soyad;
            this.Eposta = Eposta;
            this.Telefon = Telefon;
            this.Adres = Adres;
            this.SehirKodu = SehirKodu;
            this.Sehir = Sehir;
            this.IlceKodu = IlceKodu;
            this.Ilce = Ilce;
            this.Mesaj = Mesaj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlfemoIletisimResponse", WrapperNamespace="https://services.alfemo.com.tr/", IsWrapped=true)]
    public partial class AlfemoIletisimResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=0)]
        public string AlfemoIletisimResult;
        
        public AlfemoIletisimResponse() {
        }
        
        public AlfemoIletisimResponse(string AlfemoIletisimResult) {
            this.AlfemoIletisimResult = AlfemoIletisimResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlfemoUrunMontajPdf", WrapperNamespace="https://services.alfemo.com.tr/", IsWrapped=true)]
    public partial class AlfemoUrunMontajPdfRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://services.alfemo.com.tr/")]
        public B2B.ServiceQdms.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=0)]
        public string UrunKodu;
        
        public AlfemoUrunMontajPdfRequest() {
        }
        
        public AlfemoUrunMontajPdfRequest(B2B.ServiceQdms.AuthHeader AuthHeader, string UrunKodu) {
            this.AuthHeader = AuthHeader;
            this.UrunKodu = UrunKodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlfemoUrunMontajPdfResponse", WrapperNamespace="https://services.alfemo.com.tr/", IsWrapped=true)]
    public partial class AlfemoUrunMontajPdfResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] AlfemoUrunMontajPdfResult;
        
        public AlfemoUrunMontajPdfResponse() {
        }
        
        public AlfemoUrunMontajPdfResponse(byte[] AlfemoUrunMontajPdfResult) {
            this.AlfemoUrunMontajPdfResult = AlfemoUrunMontajPdfResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlfemoUrunPdf", WrapperNamespace="https://services.alfemo.com.tr/", IsWrapped=true)]
    public partial class AlfemoUrunPdfRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://services.alfemo.com.tr/")]
        public B2B.ServiceQdms.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=0)]
        public string urunKodu;
        
        public AlfemoUrunPdfRequest() {
        }
        
        public AlfemoUrunPdfRequest(B2B.ServiceQdms.AuthHeader AuthHeader, string urunKodu) {
            this.AuthHeader = AuthHeader;
            this.urunKodu = urunKodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlfemoUrunPdfResponse", WrapperNamespace="https://services.alfemo.com.tr/", IsWrapped=true)]
    public partial class AlfemoUrunPdfResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.alfemo.com.tr/", Order=0)]
        public string AlfemoUrunPdfResult;
        
        public AlfemoUrunPdfResponse() {
        }
        
        public AlfemoUrunPdfResponse(string AlfemoUrunPdfResult) {
            this.AlfemoUrunPdfResult = AlfemoUrunPdfResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlfemoWebSiteServiceSoapChannel : B2B.ServiceQdms.AlfemoWebSiteServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlfemoWebSiteServiceSoapClient : System.ServiceModel.ClientBase<B2B.ServiceQdms.AlfemoWebSiteServiceSoap>, B2B.ServiceQdms.AlfemoWebSiteServiceSoap {
        
        public AlfemoWebSiteServiceSoapClient() {
        }
        
        public AlfemoWebSiteServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlfemoWebSiteServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlfemoWebSiteServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlfemoWebSiteServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2B.ServiceQdms.AlfemoFiyatListesiJSONResponse B2B.ServiceQdms.AlfemoWebSiteServiceSoap.AlfemoFiyatListesiJSON(B2B.ServiceQdms.AlfemoFiyatListesiJSONRequest request) {
            return base.Channel.AlfemoFiyatListesiJSON(request);
        }
        
        public string AlfemoFiyatListesiJSON(B2B.ServiceQdms.AuthHeader AuthHeader, string UrunKodu) {
            B2B.ServiceQdms.AlfemoFiyatListesiJSONRequest inValue = new B2B.ServiceQdms.AlfemoFiyatListesiJSONRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.UrunKodu = UrunKodu;
            B2B.ServiceQdms.AlfemoFiyatListesiJSONResponse retVal = ((B2B.ServiceQdms.AlfemoWebSiteServiceSoap)(this)).AlfemoFiyatListesiJSON(inValue);
            return retVal.AlfemoFiyatListesiJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoFiyatListesiJSONResponse> B2B.ServiceQdms.AlfemoWebSiteServiceSoap.AlfemoFiyatListesiJSONAsync(B2B.ServiceQdms.AlfemoFiyatListesiJSONRequest request) {
            return base.Channel.AlfemoFiyatListesiJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoFiyatListesiJSONResponse> AlfemoFiyatListesiJSONAsync(B2B.ServiceQdms.AuthHeader AuthHeader, string UrunKodu) {
            B2B.ServiceQdms.AlfemoFiyatListesiJSONRequest inValue = new B2B.ServiceQdms.AlfemoFiyatListesiJSONRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.UrunKodu = UrunKodu;
            return ((B2B.ServiceQdms.AlfemoWebSiteServiceSoap)(this)).AlfemoFiyatListesiJSONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2B.ServiceQdms.AlfemoDepoStokJSONResponse B2B.ServiceQdms.AlfemoWebSiteServiceSoap.AlfemoDepoStokJSON(B2B.ServiceQdms.AlfemoDepoStokJSONRequest request) {
            return base.Channel.AlfemoDepoStokJSON(request);
        }
        
        public string AlfemoDepoStokJSON(B2B.ServiceQdms.AuthHeader AuthHeader, string UrunKodu) {
            B2B.ServiceQdms.AlfemoDepoStokJSONRequest inValue = new B2B.ServiceQdms.AlfemoDepoStokJSONRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.UrunKodu = UrunKodu;
            B2B.ServiceQdms.AlfemoDepoStokJSONResponse retVal = ((B2B.ServiceQdms.AlfemoWebSiteServiceSoap)(this)).AlfemoDepoStokJSON(inValue);
            return retVal.AlfemoDepoStokJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoDepoStokJSONResponse> B2B.ServiceQdms.AlfemoWebSiteServiceSoap.AlfemoDepoStokJSONAsync(B2B.ServiceQdms.AlfemoDepoStokJSONRequest request) {
            return base.Channel.AlfemoDepoStokJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoDepoStokJSONResponse> AlfemoDepoStokJSONAsync(B2B.ServiceQdms.AuthHeader AuthHeader, string UrunKodu) {
            B2B.ServiceQdms.AlfemoDepoStokJSONRequest inValue = new B2B.ServiceQdms.AlfemoDepoStokJSONRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.UrunKodu = UrunKodu;
            return ((B2B.ServiceQdms.AlfemoWebSiteServiceSoap)(this)).AlfemoDepoStokJSONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2B.ServiceQdms.AlfemoAcikSiparisJSONResponse B2B.ServiceQdms.AlfemoWebSiteServiceSoap.AlfemoAcikSiparisJSON(B2B.ServiceQdms.AlfemoAcikSiparisJSONRequest request) {
            return base.Channel.AlfemoAcikSiparisJSON(request);
        }
        
        public string AlfemoAcikSiparisJSON(B2B.ServiceQdms.AuthHeader AuthHeader, string SiparisNo) {
            B2B.ServiceQdms.AlfemoAcikSiparisJSONRequest inValue = new B2B.ServiceQdms.AlfemoAcikSiparisJSONRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.SiparisNo = SiparisNo;
            B2B.ServiceQdms.AlfemoAcikSiparisJSONResponse retVal = ((B2B.ServiceQdms.AlfemoWebSiteServiceSoap)(this)).AlfemoAcikSiparisJSON(inValue);
            return retVal.AlfemoAcikSiparisJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoAcikSiparisJSONResponse> B2B.ServiceQdms.AlfemoWebSiteServiceSoap.AlfemoAcikSiparisJSONAsync(B2B.ServiceQdms.AlfemoAcikSiparisJSONRequest request) {
            return base.Channel.AlfemoAcikSiparisJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoAcikSiparisJSONResponse> AlfemoAcikSiparisJSONAsync(B2B.ServiceQdms.AuthHeader AuthHeader, string SiparisNo) {
            B2B.ServiceQdms.AlfemoAcikSiparisJSONRequest inValue = new B2B.ServiceQdms.AlfemoAcikSiparisJSONRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.SiparisNo = SiparisNo;
            return ((B2B.ServiceQdms.AlfemoWebSiteServiceSoap)(this)).AlfemoAcikSiparisJSONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2B.ServiceQdms.AlfemoSiparisSorgulamaJSONResponse B2B.ServiceQdms.AlfemoWebSiteServiceSoap.AlfemoSiparisSorgulamaJSON(B2B.ServiceQdms.AlfemoSiparisSorgulamaJSONRequest request) {
            return base.Channel.AlfemoSiparisSorgulamaJSON(request);
        }
        
        public string AlfemoSiparisSorgulamaJSON(B2B.ServiceQdms.AuthHeader AuthHeader, string SiparisNo) {
            B2B.ServiceQdms.AlfemoSiparisSorgulamaJSONRequest inValue = new B2B.ServiceQdms.AlfemoSiparisSorgulamaJSONRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.SiparisNo = SiparisNo;
            B2B.ServiceQdms.AlfemoSiparisSorgulamaJSONResponse retVal = ((B2B.ServiceQdms.AlfemoWebSiteServiceSoap)(this)).AlfemoSiparisSorgulamaJSON(inValue);
            return retVal.AlfemoSiparisSorgulamaJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoSiparisSorgulamaJSONResponse> B2B.ServiceQdms.AlfemoWebSiteServiceSoap.AlfemoSiparisSorgulamaJSONAsync(B2B.ServiceQdms.AlfemoSiparisSorgulamaJSONRequest request) {
            return base.Channel.AlfemoSiparisSorgulamaJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoSiparisSorgulamaJSONResponse> AlfemoSiparisSorgulamaJSONAsync(B2B.ServiceQdms.AuthHeader AuthHeader, string SiparisNo) {
            B2B.ServiceQdms.AlfemoSiparisSorgulamaJSONRequest inValue = new B2B.ServiceQdms.AlfemoSiparisSorgulamaJSONRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.SiparisNo = SiparisNo;
            return ((B2B.ServiceQdms.AlfemoWebSiteServiceSoap)(this)).AlfemoSiparisSorgulamaJSONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2B.ServiceQdms.AlfemoUrunJSONResponse B2B.ServiceQdms.AlfemoWebSiteServiceSoap.AlfemoUrunJSON(B2B.ServiceQdms.AlfemoUrunJSONRequest request) {
            return base.Channel.AlfemoUrunJSON(request);
        }
        
        public string AlfemoUrunJSON(B2B.ServiceQdms.AuthHeader AuthHeader, string UrunKodu) {
            B2B.ServiceQdms.AlfemoUrunJSONRequest inValue = new B2B.ServiceQdms.AlfemoUrunJSONRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.UrunKodu = UrunKodu;
            B2B.ServiceQdms.AlfemoUrunJSONResponse retVal = ((B2B.ServiceQdms.AlfemoWebSiteServiceSoap)(this)).AlfemoUrunJSON(inValue);
            return retVal.AlfemoUrunJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoUrunJSONResponse> B2B.ServiceQdms.AlfemoWebSiteServiceSoap.AlfemoUrunJSONAsync(B2B.ServiceQdms.AlfemoUrunJSONRequest request) {
            return base.Channel.AlfemoUrunJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoUrunJSONResponse> AlfemoUrunJSONAsync(B2B.ServiceQdms.AuthHeader AuthHeader, string UrunKodu) {
            B2B.ServiceQdms.AlfemoUrunJSONRequest inValue = new B2B.ServiceQdms.AlfemoUrunJSONRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.UrunKodu = UrunKodu;
            return ((B2B.ServiceQdms.AlfemoWebSiteServiceSoap)(this)).AlfemoUrunJSONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2B.ServiceQdms.AlfemoIletisimResponse B2B.ServiceQdms.AlfemoWebSiteServiceSoap.AlfemoIletisim(B2B.ServiceQdms.AlfemoIletisimRequest request) {
            return base.Channel.AlfemoIletisim(request);
        }
        
        public string AlfemoIletisim(B2B.ServiceQdms.AuthHeader AuthHeader, string Konu, string AltKonu, string Ad, string Soyad, string Eposta, string Telefon, string Adres, string SehirKodu, string Sehir, string IlceKodu, string Ilce, string Mesaj) {
            B2B.ServiceQdms.AlfemoIletisimRequest inValue = new B2B.ServiceQdms.AlfemoIletisimRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.Konu = Konu;
            inValue.AltKonu = AltKonu;
            inValue.Ad = Ad;
            inValue.Soyad = Soyad;
            inValue.Eposta = Eposta;
            inValue.Telefon = Telefon;
            inValue.Adres = Adres;
            inValue.SehirKodu = SehirKodu;
            inValue.Sehir = Sehir;
            inValue.IlceKodu = IlceKodu;
            inValue.Ilce = Ilce;
            inValue.Mesaj = Mesaj;
            B2B.ServiceQdms.AlfemoIletisimResponse retVal = ((B2B.ServiceQdms.AlfemoWebSiteServiceSoap)(this)).AlfemoIletisim(inValue);
            return retVal.AlfemoIletisimResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoIletisimResponse> B2B.ServiceQdms.AlfemoWebSiteServiceSoap.AlfemoIletisimAsync(B2B.ServiceQdms.AlfemoIletisimRequest request) {
            return base.Channel.AlfemoIletisimAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoIletisimResponse> AlfemoIletisimAsync(B2B.ServiceQdms.AuthHeader AuthHeader, string Konu, string AltKonu, string Ad, string Soyad, string Eposta, string Telefon, string Adres, string SehirKodu, string Sehir, string IlceKodu, string Ilce, string Mesaj) {
            B2B.ServiceQdms.AlfemoIletisimRequest inValue = new B2B.ServiceQdms.AlfemoIletisimRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.Konu = Konu;
            inValue.AltKonu = AltKonu;
            inValue.Ad = Ad;
            inValue.Soyad = Soyad;
            inValue.Eposta = Eposta;
            inValue.Telefon = Telefon;
            inValue.Adres = Adres;
            inValue.SehirKodu = SehirKodu;
            inValue.Sehir = Sehir;
            inValue.IlceKodu = IlceKodu;
            inValue.Ilce = Ilce;
            inValue.Mesaj = Mesaj;
            return ((B2B.ServiceQdms.AlfemoWebSiteServiceSoap)(this)).AlfemoIletisimAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2B.ServiceQdms.AlfemoUrunMontajPdfResponse B2B.ServiceQdms.AlfemoWebSiteServiceSoap.AlfemoUrunMontajPdf(B2B.ServiceQdms.AlfemoUrunMontajPdfRequest request) {
            return base.Channel.AlfemoUrunMontajPdf(request);
        }
        
        public byte[] AlfemoUrunMontajPdf(B2B.ServiceQdms.AuthHeader AuthHeader, string UrunKodu) {
            B2B.ServiceQdms.AlfemoUrunMontajPdfRequest inValue = new B2B.ServiceQdms.AlfemoUrunMontajPdfRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.UrunKodu = UrunKodu;
            B2B.ServiceQdms.AlfemoUrunMontajPdfResponse retVal = ((B2B.ServiceQdms.AlfemoWebSiteServiceSoap)(this)).AlfemoUrunMontajPdf(inValue);
            return retVal.AlfemoUrunMontajPdfResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoUrunMontajPdfResponse> B2B.ServiceQdms.AlfemoWebSiteServiceSoap.AlfemoUrunMontajPdfAsync(B2B.ServiceQdms.AlfemoUrunMontajPdfRequest request) {
            return base.Channel.AlfemoUrunMontajPdfAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoUrunMontajPdfResponse> AlfemoUrunMontajPdfAsync(B2B.ServiceQdms.AuthHeader AuthHeader, string UrunKodu) {
            B2B.ServiceQdms.AlfemoUrunMontajPdfRequest inValue = new B2B.ServiceQdms.AlfemoUrunMontajPdfRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.UrunKodu = UrunKodu;
            return ((B2B.ServiceQdms.AlfemoWebSiteServiceSoap)(this)).AlfemoUrunMontajPdfAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2B.ServiceQdms.AlfemoUrunPdfResponse B2B.ServiceQdms.AlfemoWebSiteServiceSoap.AlfemoUrunPdf(B2B.ServiceQdms.AlfemoUrunPdfRequest request) {
            return base.Channel.AlfemoUrunPdf(request);
        }
        
        public string AlfemoUrunPdf(B2B.ServiceQdms.AuthHeader AuthHeader, string urunKodu) {
            B2B.ServiceQdms.AlfemoUrunPdfRequest inValue = new B2B.ServiceQdms.AlfemoUrunPdfRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.urunKodu = urunKodu;
            B2B.ServiceQdms.AlfemoUrunPdfResponse retVal = ((B2B.ServiceQdms.AlfemoWebSiteServiceSoap)(this)).AlfemoUrunPdf(inValue);
            return retVal.AlfemoUrunPdfResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoUrunPdfResponse> B2B.ServiceQdms.AlfemoWebSiteServiceSoap.AlfemoUrunPdfAsync(B2B.ServiceQdms.AlfemoUrunPdfRequest request) {
            return base.Channel.AlfemoUrunPdfAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2B.ServiceQdms.AlfemoUrunPdfResponse> AlfemoUrunPdfAsync(B2B.ServiceQdms.AuthHeader AuthHeader, string urunKodu) {
            B2B.ServiceQdms.AlfemoUrunPdfRequest inValue = new B2B.ServiceQdms.AlfemoUrunPdfRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.urunKodu = urunKodu;
            return ((B2B.ServiceQdms.AlfemoWebSiteServiceSoap)(this)).AlfemoUrunPdfAsync(inValue);
        }
    }
}
