//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.ServiceStock {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceStock.WebServiceStockSoap")]
    public interface WebServiceStockSoap {
        
        // CODEGEN: Generating message contract since message GetObservedStockRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObservedStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        B2B.ServiceStock.GetObservedStockResponse GetObservedStock(B2B.ServiceStock.GetObservedStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObservedStock", ReplyAction="*")]
        System.Threading.Tasks.Task<B2B.ServiceStock.GetObservedStockResponse> GetObservedStockAsync(B2B.ServiceStock.GetObservedStockRequest request);
        
        // CODEGEN: Generating message contract since message GetStoreObservedStockRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStoreObservedStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        B2B.ServiceStock.GetStoreObservedStockResponse GetStoreObservedStock(B2B.ServiceStock.GetStoreObservedStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStoreObservedStock", ReplyAction="*")]
        System.Threading.Tasks.Task<B2B.ServiceStock.GetStoreObservedStockResponse> GetStoreObservedStockAsync(B2B.ServiceStock.GetStoreObservedStockRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetObservedStock", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetObservedStockRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public B2B.ServiceStock.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string iv_sortl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string iv_mvgr2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string iv_mvgr3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string iv_mvgr4;
        
        public GetObservedStockRequest() {
        }
        
        public GetObservedStockRequest(B2B.ServiceStock.AuthHeader AuthHeader, string iv_sortl, string iv_mvgr2, string iv_mvgr3, string iv_mvgr4) {
            this.AuthHeader = AuthHeader;
            this.iv_sortl = iv_sortl;
            this.iv_mvgr2 = iv_mvgr2;
            this.iv_mvgr3 = iv_mvgr3;
            this.iv_mvgr4 = iv_mvgr4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetObservedStockResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetObservedStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetObservedStockResult;
        
        public GetObservedStockResponse() {
        }
        
        public GetObservedStockResponse(string GetObservedStockResult) {
            this.GetObservedStockResult = GetObservedStockResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStoreObservedStock", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStoreObservedStockRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public B2B.ServiceStock.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string iv_lgort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string iv_mvgr2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string iv_mvgr3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string iv_mvgr4;
        
        public GetStoreObservedStockRequest() {
        }
        
        public GetStoreObservedStockRequest(B2B.ServiceStock.AuthHeader AuthHeader, string iv_lgort, string iv_mvgr2, string iv_mvgr3, string iv_mvgr4) {
            this.AuthHeader = AuthHeader;
            this.iv_lgort = iv_lgort;
            this.iv_mvgr2 = iv_mvgr2;
            this.iv_mvgr3 = iv_mvgr3;
            this.iv_mvgr4 = iv_mvgr4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStoreObservedStockResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStoreObservedStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetStoreObservedStockResult;
        
        public GetStoreObservedStockResponse() {
        }
        
        public GetStoreObservedStockResponse(string GetStoreObservedStockResult) {
            this.GetStoreObservedStockResult = GetStoreObservedStockResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceStockSoapChannel : B2B.ServiceStock.WebServiceStockSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceStockSoapClient : System.ServiceModel.ClientBase<B2B.ServiceStock.WebServiceStockSoap>, B2B.ServiceStock.WebServiceStockSoap {
        
        public WebServiceStockSoapClient() {
        }
        
        public WebServiceStockSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceStockSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceStockSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceStockSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2B.ServiceStock.GetObservedStockResponse B2B.ServiceStock.WebServiceStockSoap.GetObservedStock(B2B.ServiceStock.GetObservedStockRequest request) {
            return base.Channel.GetObservedStock(request);
        }
        
        public string GetObservedStock(B2B.ServiceStock.AuthHeader AuthHeader, string iv_sortl, string iv_mvgr2, string iv_mvgr3, string iv_mvgr4) {
            B2B.ServiceStock.GetObservedStockRequest inValue = new B2B.ServiceStock.GetObservedStockRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.iv_sortl = iv_sortl;
            inValue.iv_mvgr2 = iv_mvgr2;
            inValue.iv_mvgr3 = iv_mvgr3;
            inValue.iv_mvgr4 = iv_mvgr4;
            B2B.ServiceStock.GetObservedStockResponse retVal = ((B2B.ServiceStock.WebServiceStockSoap)(this)).GetObservedStock(inValue);
            return retVal.GetObservedStockResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2B.ServiceStock.GetObservedStockResponse> B2B.ServiceStock.WebServiceStockSoap.GetObservedStockAsync(B2B.ServiceStock.GetObservedStockRequest request) {
            return base.Channel.GetObservedStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2B.ServiceStock.GetObservedStockResponse> GetObservedStockAsync(B2B.ServiceStock.AuthHeader AuthHeader, string iv_sortl, string iv_mvgr2, string iv_mvgr3, string iv_mvgr4) {
            B2B.ServiceStock.GetObservedStockRequest inValue = new B2B.ServiceStock.GetObservedStockRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.iv_sortl = iv_sortl;
            inValue.iv_mvgr2 = iv_mvgr2;
            inValue.iv_mvgr3 = iv_mvgr3;
            inValue.iv_mvgr4 = iv_mvgr4;
            return ((B2B.ServiceStock.WebServiceStockSoap)(this)).GetObservedStockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2B.ServiceStock.GetStoreObservedStockResponse B2B.ServiceStock.WebServiceStockSoap.GetStoreObservedStock(B2B.ServiceStock.GetStoreObservedStockRequest request) {
            return base.Channel.GetStoreObservedStock(request);
        }
        
        public string GetStoreObservedStock(B2B.ServiceStock.AuthHeader AuthHeader, string iv_lgort, string iv_mvgr2, string iv_mvgr3, string iv_mvgr4) {
            B2B.ServiceStock.GetStoreObservedStockRequest inValue = new B2B.ServiceStock.GetStoreObservedStockRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.iv_lgort = iv_lgort;
            inValue.iv_mvgr2 = iv_mvgr2;
            inValue.iv_mvgr3 = iv_mvgr3;
            inValue.iv_mvgr4 = iv_mvgr4;
            B2B.ServiceStock.GetStoreObservedStockResponse retVal = ((B2B.ServiceStock.WebServiceStockSoap)(this)).GetStoreObservedStock(inValue);
            return retVal.GetStoreObservedStockResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2B.ServiceStock.GetStoreObservedStockResponse> B2B.ServiceStock.WebServiceStockSoap.GetStoreObservedStockAsync(B2B.ServiceStock.GetStoreObservedStockRequest request) {
            return base.Channel.GetStoreObservedStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2B.ServiceStock.GetStoreObservedStockResponse> GetStoreObservedStockAsync(B2B.ServiceStock.AuthHeader AuthHeader, string iv_lgort, string iv_mvgr2, string iv_mvgr3, string iv_mvgr4) {
            B2B.ServiceStock.GetStoreObservedStockRequest inValue = new B2B.ServiceStock.GetStoreObservedStockRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.iv_lgort = iv_lgort;
            inValue.iv_mvgr2 = iv_mvgr2;
            inValue.iv_mvgr3 = iv_mvgr3;
            inValue.iv_mvgr4 = iv_mvgr4;
            return ((B2B.ServiceStock.WebServiceStockSoap)(this)).GetStoreObservedStockAsync(inValue);
        }
    }
}
