//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.ServiceMalzeme {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMalzeme.WebServiceMalzemeSoap")]
    public interface WebServiceMalzemeSoap {
        
        // CODEGEN: Generating message contract since message GelMaterialRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GelMaterial", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        B2B.ServiceMalzeme.GelMaterialResponse GelMaterial(B2B.ServiceMalzeme.GelMaterialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GelMaterial", ReplyAction="*")]
        System.Threading.Tasks.Task<B2B.ServiceMalzeme.GelMaterialResponse> GelMaterialAsync(B2B.ServiceMalzeme.GelMaterialRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GelMaterial", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GelMaterialRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public B2B.ServiceMalzeme.AuthHeader AuthHeader;
        
        public GelMaterialRequest() {
        }
        
        public GelMaterialRequest(B2B.ServiceMalzeme.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GelMaterialResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GelMaterialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GelMaterialResult;
        
        public GelMaterialResponse() {
        }
        
        public GelMaterialResponse(string GelMaterialResult) {
            this.GelMaterialResult = GelMaterialResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMalzemeSoapChannel : B2B.ServiceMalzeme.WebServiceMalzemeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMalzemeSoapClient : System.ServiceModel.ClientBase<B2B.ServiceMalzeme.WebServiceMalzemeSoap>, B2B.ServiceMalzeme.WebServiceMalzemeSoap {
        
        public WebServiceMalzemeSoapClient() {
        }
        
        public WebServiceMalzemeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMalzemeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMalzemeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMalzemeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2B.ServiceMalzeme.GelMaterialResponse B2B.ServiceMalzeme.WebServiceMalzemeSoap.GelMaterial(B2B.ServiceMalzeme.GelMaterialRequest request) {
            return base.Channel.GelMaterial(request);
        }
        
        public string GelMaterial(B2B.ServiceMalzeme.AuthHeader AuthHeader) {
            B2B.ServiceMalzeme.GelMaterialRequest inValue = new B2B.ServiceMalzeme.GelMaterialRequest();
            inValue.AuthHeader = AuthHeader;
            B2B.ServiceMalzeme.GelMaterialResponse retVal = ((B2B.ServiceMalzeme.WebServiceMalzemeSoap)(this)).GelMaterial(inValue);
            return retVal.GelMaterialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2B.ServiceMalzeme.GelMaterialResponse> B2B.ServiceMalzeme.WebServiceMalzemeSoap.GelMaterialAsync(B2B.ServiceMalzeme.GelMaterialRequest request) {
            return base.Channel.GelMaterialAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2B.ServiceMalzeme.GelMaterialResponse> GelMaterialAsync(B2B.ServiceMalzeme.AuthHeader AuthHeader) {
            B2B.ServiceMalzeme.GelMaterialRequest inValue = new B2B.ServiceMalzeme.GelMaterialRequest();
            inValue.AuthHeader = AuthHeader;
            return ((B2B.ServiceMalzeme.WebServiceMalzemeSoap)(this)).GelMaterialAsync(inValue);
        }
    }
}
