//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.ServiceColumn {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceColumn.WebServiceColumnSoap")]
    public interface WebServiceColumnSoap {
        
        // CODEGEN: Generating message contract since message GetColumnNameRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetColumnName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        B2B.ServiceColumn.GetColumnNameResponse GetColumnName(B2B.ServiceColumn.GetColumnNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetColumnName", ReplyAction="*")]
        System.Threading.Tasks.Task<B2B.ServiceColumn.GetColumnNameResponse> GetColumnNameAsync(B2B.ServiceColumn.GetColumnNameRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetColumnName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetColumnNameRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public B2B.ServiceColumn.AuthHeader AuthHeader;
        
        public GetColumnNameRequest() {
        }
        
        public GetColumnNameRequest(B2B.ServiceColumn.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetColumnNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetColumnNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetColumnNameResult;
        
        public GetColumnNameResponse() {
        }
        
        public GetColumnNameResponse(string GetColumnNameResult) {
            this.GetColumnNameResult = GetColumnNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceColumnSoapChannel : B2B.ServiceColumn.WebServiceColumnSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceColumnSoapClient : System.ServiceModel.ClientBase<B2B.ServiceColumn.WebServiceColumnSoap>, B2B.ServiceColumn.WebServiceColumnSoap {
        
        public WebServiceColumnSoapClient() {
        }
        
        public WebServiceColumnSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceColumnSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceColumnSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceColumnSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2B.ServiceColumn.GetColumnNameResponse B2B.ServiceColumn.WebServiceColumnSoap.GetColumnName(B2B.ServiceColumn.GetColumnNameRequest request) {
            return base.Channel.GetColumnName(request);
        }
        
        public string GetColumnName(B2B.ServiceColumn.AuthHeader AuthHeader) {
            B2B.ServiceColumn.GetColumnNameRequest inValue = new B2B.ServiceColumn.GetColumnNameRequest();
            inValue.AuthHeader = AuthHeader;
            B2B.ServiceColumn.GetColumnNameResponse retVal = ((B2B.ServiceColumn.WebServiceColumnSoap)(this)).GetColumnName(inValue);
            return retVal.GetColumnNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2B.ServiceColumn.GetColumnNameResponse> B2B.ServiceColumn.WebServiceColumnSoap.GetColumnNameAsync(B2B.ServiceColumn.GetColumnNameRequest request) {
            return base.Channel.GetColumnNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2B.ServiceColumn.GetColumnNameResponse> GetColumnNameAsync(B2B.ServiceColumn.AuthHeader AuthHeader) {
            B2B.ServiceColumn.GetColumnNameRequest inValue = new B2B.ServiceColumn.GetColumnNameRequest();
            inValue.AuthHeader = AuthHeader;
            return ((B2B.ServiceColumn.WebServiceColumnSoap)(this)).GetColumnNameAsync(inValue);
        }
    }
}
