//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.ServiceAccount {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAccount.WebServiceCariSoap")]
    public interface WebServiceCariSoap {
        
        // CODEGEN: Generating message contract since message AccountStatementRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccountStatement", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        B2B.ServiceAccount.AccountStatementResponse AccountStatement(B2B.ServiceAccount.AccountStatementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccountStatement", ReplyAction="*")]
        System.Threading.Tasks.Task<B2B.ServiceAccount.AccountStatementResponse> AccountStatementAsync(B2B.ServiceAccount.AccountStatementRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AccountStatement", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AccountStatementRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public B2B.ServiceAccount.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string iv_kunnr;
        
        public AccountStatementRequest() {
        }
        
        public AccountStatementRequest(B2B.ServiceAccount.AuthHeader AuthHeader, string iv_kunnr) {
            this.AuthHeader = AuthHeader;
            this.iv_kunnr = iv_kunnr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AccountStatementResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AccountStatementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AccountStatementResult;
        
        public AccountStatementResponse() {
        }
        
        public AccountStatementResponse(string AccountStatementResult) {
            this.AccountStatementResult = AccountStatementResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceCariSoapChannel : B2B.ServiceAccount.WebServiceCariSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceCariSoapClient : System.ServiceModel.ClientBase<B2B.ServiceAccount.WebServiceCariSoap>, B2B.ServiceAccount.WebServiceCariSoap {
        
        public WebServiceCariSoapClient() {
        }
        
        public WebServiceCariSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceCariSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCariSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCariSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2B.ServiceAccount.AccountStatementResponse B2B.ServiceAccount.WebServiceCariSoap.AccountStatement(B2B.ServiceAccount.AccountStatementRequest request) {
            return base.Channel.AccountStatement(request);
        }
        
        public string AccountStatement(B2B.ServiceAccount.AuthHeader AuthHeader, string iv_kunnr) {
            B2B.ServiceAccount.AccountStatementRequest inValue = new B2B.ServiceAccount.AccountStatementRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.iv_kunnr = iv_kunnr;
            B2B.ServiceAccount.AccountStatementResponse retVal = ((B2B.ServiceAccount.WebServiceCariSoap)(this)).AccountStatement(inValue);
            return retVal.AccountStatementResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2B.ServiceAccount.AccountStatementResponse> B2B.ServiceAccount.WebServiceCariSoap.AccountStatementAsync(B2B.ServiceAccount.AccountStatementRequest request) {
            return base.Channel.AccountStatementAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2B.ServiceAccount.AccountStatementResponse> AccountStatementAsync(B2B.ServiceAccount.AuthHeader AuthHeader, string iv_kunnr) {
            B2B.ServiceAccount.AccountStatementRequest inValue = new B2B.ServiceAccount.AccountStatementRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.iv_kunnr = iv_kunnr;
            return ((B2B.ServiceAccount.WebServiceCariSoap)(this)).AccountStatementAsync(inValue);
        }
    }
}
