//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.ServicePrice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePrice.WebServicePriceSoap")]
    public interface WebServicePriceSoap {
        
        // CODEGEN: Generating message contract since message GetProductPriceRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductPrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        B2B.ServicePrice.GetProductPriceResponse GetProductPrice(B2B.ServicePrice.GetProductPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<B2B.ServicePrice.GetProductPriceResponse> GetProductPriceAsync(B2B.ServicePrice.GetProductPriceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductPrice", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProductPriceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public B2B.ServicePrice.AuthHeader AuthHeader;
        
        public GetProductPriceRequest() {
        }
        
        public GetProductPriceRequest(B2B.ServicePrice.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductPriceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProductPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetProductPriceResult;
        
        public GetProductPriceResponse() {
        }
        
        public GetProductPriceResponse(string GetProductPriceResult) {
            this.GetProductPriceResult = GetProductPriceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePriceSoapChannel : B2B.ServicePrice.WebServicePriceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePriceSoapClient : System.ServiceModel.ClientBase<B2B.ServicePrice.WebServicePriceSoap>, B2B.ServicePrice.WebServicePriceSoap {
        
        public WebServicePriceSoapClient() {
        }
        
        public WebServicePriceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePriceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePriceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePriceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2B.ServicePrice.GetProductPriceResponse B2B.ServicePrice.WebServicePriceSoap.GetProductPrice(B2B.ServicePrice.GetProductPriceRequest request) {
            return base.Channel.GetProductPrice(request);
        }
        
        public string GetProductPrice(B2B.ServicePrice.AuthHeader AuthHeader) {
            B2B.ServicePrice.GetProductPriceRequest inValue = new B2B.ServicePrice.GetProductPriceRequest();
            inValue.AuthHeader = AuthHeader;
            B2B.ServicePrice.GetProductPriceResponse retVal = ((B2B.ServicePrice.WebServicePriceSoap)(this)).GetProductPrice(inValue);
            return retVal.GetProductPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2B.ServicePrice.GetProductPriceResponse> B2B.ServicePrice.WebServicePriceSoap.GetProductPriceAsync(B2B.ServicePrice.GetProductPriceRequest request) {
            return base.Channel.GetProductPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2B.ServicePrice.GetProductPriceResponse> GetProductPriceAsync(B2B.ServicePrice.AuthHeader AuthHeader) {
            B2B.ServicePrice.GetProductPriceRequest inValue = new B2B.ServicePrice.GetProductPriceRequest();
            inValue.AuthHeader = AuthHeader;
            return ((B2B.ServicePrice.WebServicePriceSoap)(this)).GetProductPriceAsync(inValue);
        }
    }
}
